version: 2

updates:
  # GHA
  # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "23:00"

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "23:00"

