
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "23:00"

  - package-ecosystem: "pip"
    directories:
      - "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "23:00"
