name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'python/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    defaults:
      run:
        working-directory: python
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup
        run: make .venv

      - name: Generate docs
        run: make rtd-html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./python/docs/_build/html
          cname: sdk.rootsignals.ai