name: Run tests and verify

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-sdk-python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: sdk-python-${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            sdk-python-${{ runner.os }}-python-${{ matrix.python-version }}-

      - name: Setup
        run: make .venv

      - name: Ensure generated schema matches what we have
        run: |
          make generate-openapi-client
          sudo chown -R `whoami` src/root/generated
          make fix-openapi-client
          git diff src/root/generated || \
            ( echo "Generated OpenAPI has changed. Please run 'make generate' and commit the changes." && exit 1 )

        # NB: separate chown step is needed as docker for some reason
        # changes uid of the generated files when run in GHA, but not
        # when I run it locally.

      - name: Run the lint+tests
        if: |
          !(github.event_name == 'push' && github.ref_name == 'main')
        run: make

      - name: Build dist
        if: |
          !(github.event_name == 'push' && github.ref_name == 'main')
        run: make dist

# TODO: Do we want to make publish happen here too?
